// <auto-generated />
namespace MvcApplication1.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class asd3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(asd3));
        
        string IMigrationMetadata.Id
        {
            get { return "201307101702567_asd3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
