// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class textmessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(textmessage));
        
        string IMigrationMetadata.Id
        {
            get { return "201309191433420_textmessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
