// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dunno1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dunno1));
        
        string IMigrationMetadata.Id
        {
            get { return "201308191232151_dunno1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
