// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removecategories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecategories));
        
        string IMigrationMetadata.Id
        {
            get { return "201308281218073_remove categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
