// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class enabled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enabled));
        
        string IMigrationMetadata.Id
        {
            get { return "201309240907517_enabled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
