// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class textupdated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(textupdated));
        
        string IMigrationMetadata.Id
        {
            get { return "201309250932142_text updated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
