// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dunno4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dunno4));
        
        string IMigrationMetadata.Id
        {
            get { return "201309280851004_dunno4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
