// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class apiId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(apiId));
        
        string IMigrationMetadata.Id
        {
            get { return "201309200858496_apiId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
