// <auto-generated />
namespace MvcKissApplication.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class hoursinmission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hoursinmission));
        
        string IMigrationMetadata.Id
        {
            get { return "201308230925304_hours in mission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
