// <auto-generated />
namespace MvcWebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Performerfreetimes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Performerfreetimes));
        
        string IMigrationMetadata.Id
        {
            get { return "201306181104194_Performer free times"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
