// <auto-generated />
namespace MvcWebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class timefree : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(timefree));
        
        string IMigrationMetadata.Id
        {
            get { return "201306201050454_timefree"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
