// <auto-generated />
namespace MvcWebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Clienttypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Clienttypes));
        
        string IMigrationMetadata.Id
        {
            get { return "201306171212249_Client types"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
