// <auto-generated />
namespace MvcWebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Administrators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Administrators));
        
        string IMigrationMetadata.Id
        {
            get { return "201305161231305_Administrators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
