// <auto-generated />
namespace MvcWebRole.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AssignmentClientTimeReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AssignmentClientTimeReport));
        
        string IMigrationMetadata.Id
        {
            get { return "201305200801289_Assignment Client TimeReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
