// <auto-generated />
namespace PageAndServices.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class employeedescription : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(employeedescription));
        
        string IMigrationMetadata.Id
        {
            get { return "201310111058148_employee description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
