// <auto-generated />
namespace PageAndServices.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class categoryurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201310072035180_category url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
