// <auto-generated />
namespace PageAndServices.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class categoryorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(categoryorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201310071945053_category order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
